### ISSUE TITLE
0.6 version in "zip64" mode breaks zip format

### ISSUE THREAD

**Issue by git-neo-si** [McNetic/PHPZipStreamer#18]
Strange bug apperad in 0.6 (in 0.5 all is OK), which breaks zip structure in such way that the zip file size is a bit larger, and zip structure is broken. This happens ONLY when using "zip64" mode.
When "zip64" is disabled, this bug is not present.

Bug is reproducible if directory structure, which is to be zipped, contains only files or only folders. If structure contains both (file and folder) anywhere in directory tree, the resulting zip is zip is OK and fully extractable.

Example (resulting zip file is OK):
Pod1/Sub1/file1.img
Pod1/Sub1/file2.img
Pod1/Sub1/SubSub1/file3.img

Example (resulting zip broken):
Pod1/Sub1/file1.img
Pod1/Sub1/file2.img

Optional workaround: create empty folder, which is not included into zip file:
Pod1/Sub1/file1.img
Pod1/Sub1/file2.img
Pod1/Sub1/EmptyDir

**Comment by McNetic** [comment]
Please comment on the issue; if I don't get feedback within a few days, I will close this issue (but you can of course reopen if the issue persists).

**Comment by git-neo-si** [comment]
Hello, 

I'll recheck all the options we use and get back with results. 

Tnx for "a ping". 

Dne 2015-02-05 14:30, je McNetic napisal(a): 

> Please comment on the issue; if I don't get feedback within a few days, I will close this issue (but you can of course reopen if the issue persists). 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Robert
 

Links:
------
[1]
https://github.com/McNetic/PHPZipStreamer/issues/18#issuecomment-73045893

**Comment by vvllaadd** [comment]
The library just doesn't work with larger files, the Zip archives are corrupt. Version 0.4 which I tried worked fine.

**Comment by McNetic** [comment]
@vvllaadd: I'd be glad if you could provide more input to help me improve Zipstreamer. Currently, I do not know how you created your zip archives (there was an api change and maybe you did something wrong), and how you try to verify/unpack the generated archives (it's not possible with OSX builtin methods due to apple not implementing parts of the zip standard that are older than 20 years, see #16).

If you provide more information, I'd be glad to help and/or fix any bugs in Zipstreamer.

**Comment by vvllaadd** [comment]
@mcnetic thanks for the comeback. I'm verifying the archives using WinRAR and 7zip test functions. There is a small byte size difference between archives created with the different versions of this library. I'm in vacation right now, but I will set up a test case next week for you.

**Comment by McNetic** [comment]
Again, please comment on the issue; if I don't get feedback within a few days, I will close this issue (but you can of course reopen if the issue persists).

**Comment by McNetic** [comment]
Ok, closing this issue now. If the problem persists and you can provide more input (as requested), feel free to reopen the issue.
