### ISSUE TITLE
Updating DOS Timestamp not necessary?

### ISSUE THREAD

**Issue by saper** [McNetic/PHPZipStreamer#22]
While troubleshooting problems related to owncloud/core#10001 (FreeBSD's `libarchive` does not support ZIp64) I noticed that every time I downloaded the same file it had a different SHA-1 hash. Upon closer investigation it seems that only few bytes are changed which are timestamps.

Since someone somewhere may want to cache/store the file, I think it would be good to keep the same bytestream identical, if possible all the time. DOS timestamp looks like a feature one can live without.

**Comment by McNetic** [comment]
Well, the file mod timestamp is not optional in the zip specification. As Zipstreamer does only work on streams, it has no information about the "original" timestamps, so it has to provide current time as timestamp. The api allows, however, to provide a different timestamp for every file added, so owncloud could provide fixed (correct) timestamps for the files, anyways.

**Comment by saper** [comment]
Sure, but thus timestamp has little meaning and generating it anew causes PHP always to send a modified file. Can be a bad thing for caches like varnish or CDNs. 0x00 0x00 0x00 0x00 is also a valid timestamp :)

**Comment by McNetic** [comment]
I understand the problem, but I still think for a file generated on the fly the current time is a more sensible default than 0, and it is within responsibility of the software (in this case owncloud) to provide a different timestamp if needed.
Additionally, I would not have changed the api without notifying owncloud (I try not to change the api at all, if not necessary), so it would have to be decided by the owncloud project to change the current behaviour, anyways.
