### ISSUE TITLE
Header Content Length while file is being streamed/created.

### ISSUE THREAD

**Issue by jcloninger** [McNetic/PHPZipStreamer#26]
First, this is a great zipstreamer!  Second, this is my first github post.  
I don't know how to do pull requests, but here's something I've worked on a good amount of the day figuring out and finally got this working!  This is ONLY for non-compressed files, just STORE!

The script can't know the content length before streaming, so we need to calculate. The hard part was figuring out the overhead bytes.

Pulling from the database and inserting into the form to trigger downloading the zip, I have 3 hidden form fields for each file to send: 
- file_id (to get the name from the database later, but you could send now but I'm doing other things after this gets processed.)
- file_size_bytes (used to calculate total for header... these are already in my db and used elewhere in my app, but you could easily get this by <code>filesize($path.$filename);</code>
- file_name_length (actually NOT from database, but a jquery calulation that's added when a file is clicked to add to the "zip basket".)

POST that to the "download_zip.php" page where the ZipStreamer is configured.

$count = sizeof($_POST['file_id']); How many files...

foreach $_POST['file_size_bytes']
   $size = (total for files)

foreach $_POST['file_name_length'] gets counted for the number of characters in file names.
   $length = (total characters)
 
Then I do a simple calculation (where it took me a long time to figure out)
<pre>$size_for_header = ($count * 160) + ($length * 2) + $size + 98;</pre>

On this page, before I loop through to add the files, I have this right after the NewZipStreamer:
<pre>$zip->sendHeaders($zip_name,$size_for_header);</pre>

NEXT I modified the following in your code:
Line 136 I added $totalSize = '0'.
<pre>public function sendHeaders($archiveName = 'archive.zip', $totalSize = '0', $contentType = 'application/zip') { </pre>
Line 157 I added this:
<pre>header('Content-Length: '.$totalSize);</pre>

NOW when you are downloading a zip, you'll see the usual "X Mb / Y Gb" with an ETA depending on your browser just like with regular downloads!

I tested this thoroughly and even downloaded a 6 Gb .zip with 20 files or so (using my LAN.)  The only thing that was giving me errors is when adding files with non-ASCII characters! So I figured out it was not allowing enough bytes for those characters in the file names... I added a javascript function in the routine when counting the characters before appending the form:
<pre>function byteCountLength(str) {
    return encodeURI(str).split(/%..|./).length - 1;
}</pre>
and this counts them as an extra character when necessary... English, Russian, Chinese, Japanese...

The way I came up with the 160 & 98 in the $size_for_header calculation is I ran a 1 byte file named "1.txt" through the system. Without my modification the size of the zip was 260 bytes.  I knew there were 2 bytes per character of the file name so there's 10 bytes + another for the file data was 11 bytes for the file, 258 for the zip overhead.  I tired figuring the rest out by going through the comments in your code, but never got it to work with 2 or more files.  So I added a "2.txt" file... again with 1 byte size.  That gave me a 440 byte file when zipping both.  Back out the 22 bytes for the characters and file data, that gave me 418 bytes of overhead total.  Ok, so an extra file added was 160 more bytes overhead. Subtracted 160 from the 258 in the single file zip and that left me with 98 bytes as the base overhead for the zip (without file data and a file names.) Seems weird but that's what worked.  Keep in mind, this is ONLY for STORE and not for compression.  

To be able to send the length header while the file is being streamed WHILE being "created", we needed to know the length up front before the zip is being made.  With a little work before sending to the script, its all gravy in the end!

I hope this helps someone.
Now, if I can figure out how to keep the original file date for each file in the zip.

**Comment by McNetic** [comment]
Well, the issue tracker is actually meant for reporting bugs and requesting new features; while this is technically neither. I understand, however, your intention of sharing your work. As this is a quite special use case, I don't want to incorporate the changes into the core ZipStreamer. If you want to use it this way, you can also refrain from using the built-in sendHeaders() and completely built your own headers (there's no big magic in these).

Regarding the file dates: As ZipStreamer only works on streams, but not on files, it can not determine dates by itself (so it uses the current date/time by default). If you know the date of your files (be it from reading it from the files itself, or storing in your db), you can provide the date when adding the files to the zip like this:
```$zip->addFileFromStream($stream, $filePath, array('timestamp' => $timestamp))```

There are also some other options; check out https://github.com/McNetic/PHPZipStreamer/blob/master/MANUAL.md

**Comment by jcloninger** [comment]
Thanks.  Sorry for posting incorrectly.  Date works as you said it would.
