### ISSUE TITLE
Failed test suite

### ISSUE THREAD

**Issue by remicollet** [McNetic/PHPZipStreamer#29]
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
    
    Runtime:       PHP 5.6.17 with Xdebug 2.4.0RC3
    Configuration: /dev/shm/BUILD/PHPZipStreamer-44c99c659abf4dac92882437c1da68de824ca9d0/test/phpunit.xml
    
    RR......EE......EE..EE......EE......EE..EE....................... 65 / 94 ( 69%)
    .............................                                     94 / 94 (100%)
    
    Time: 699 ms, Memory: 30.75Mb
    
    There were 12 errors:
    
    1) ZipStreamer\TestZipStreamer::testZipfile with data set #6 (array(true, 8, 1), array(ZipStreamer\File Object (...)), 'one file (options = array(zip...RMAL))')
    http\Encoding\Stream::update(): Failed to update deflate stream: buffer error
    
    /dev/shm/BUILD/PHPZipStreamer-44c99c659abf4dac92882437c1da68de824ca9d0/src/ZipStreamer.php:673
    /dev/shm/BUILD/PHPZipStreamer-44c99c659abf4dac92882437c1da68de824ca9d0/src/ZipStreamer.php:367
    /dev/shm/BUILD/PHPZipStreamer-44c99c659abf4dac92882437c1da68de824ca9d0/src/ZipStreamer.php:216
    /dev/shm/BUILD/PHPZipStreamer-44c99c659abf4dac92882437c1da68de824ca9d0/test/ZipStreamerTest.php:348
    
    ....

And : 

    There were 2 risky tests:
    
    1) ZipStreamer\TestZipStreamer::testSendHeadersOK with data set #0 (array(), 'application/zip', 'archive.zip', 'default headers')
    Test code or tested code did not (only) close its own output buffers
    
    2) ZipStreamer\TestZipStreamer::testSendHeadersOK with data set #1 (array('file.zip', 'application/octet-stream'), 'application/octet-stream', 'file.zip', 'specific headers')
    Test code or tested code did not (only) close its own output buffers
    
    FAILURES!
    Tests: 94, Assertions: 1775, Errors: 12, Risky: 2.

Notice: this seems related to call to  \http\encoding\Stream\Deflate::update() with empty $data.

Workaround:

        return  ($data ? $this->peclDeflateStream->update($data) : $this->peclDeflateStream->update($data));

**Comment by remicollet** [comment]
@m6w6 is it expected that empty raw data raise this error (notice, dropping the call doesn't seems ok).

**Comment by m6w6** [comment]
Hm, yes, I think.

    if (strlen($data)) {
        $this->peclDeflateStream->update($data);
    }

**Comment by remicollet** [comment]
Yep...  simpler workaround.

      return ($data ? $this->peclDeflateStream->update($data) : false);
