### ISSUE TITLE
Archieves are still can't be opened by "StuffIt Expander"

### ISSUE THREAD

**Issue by radistmorse** [McNetic/PHPZipStreamer#6]
Hi again! :)
The multi-volume being fixed, the StuffIt Expander still considers the archive broken. StuffIt Expander is quite popular on macs, so I guess it's an issue.

Unfortunately, I don't own any macs, so I can't provide any additional info, other than that all the linux utilities think that the file is OK.

StuffIt has this to say:
An error occurred attempting to expand "filename"
The structure of the archive is damaged (Error #17540)

The StuffIt website says nothing of interest about "Error #17540": "Archive is broken, deal with it".

I'll try with windows version of StuffIt later, when I have access to windows machine. Hopefully I'll get some additional info.

**Comment by kassy4** [comment]
I was having the same problem with files that I had even downloaded as zips myself from Dropbox, so I knew they weren't corrupt.  I just tried http://www.izip.com/ and it works, although it mounts the zip file as a drive, which is kinda weird, but hey, great to get into the files!

**Comment by McNetic** [comment]
Meanwhile, there were some fixes in ZipStreamer, and I'm quite confident the zip files generated by the current version are really standards compliant (it's incorporated into current owncloud dev version, too). I'd be glad if you could try again and report back. Anyways, I will close this issue if there's no new input within the next few days/weeks.

**Comment by McNetic** [comment]
Ok, closing this issue now. If the problem persists and you can provide more input (as requested), feel free to reopen the issue.
